name: tests and linter
on: push
strategy:
  matrix:
    node-version: [20.x]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: my-step
        run: make test
        run: make lint